# Copyright 20 The original authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
name: Build

env:
  MAVEN_ARGS: -B -e

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Clojure ${{ matrix.java }} Leiningen
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11.0.2]
        mandrel-version: [21.2.0.0]
        lein-version: [2.9.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.0.0.2'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'
      - name: Install native-image component
        run: |
          gu install native-image
      - name: Setup Leiningen
        uses: sdkman/sdkman-action@master
        id: sdkman-lein
        with:
          candidate: lein
          version: ${{matrix.lein-version}}
      - run: |
          lein test
          lein native-image
